### ISSUE TITLE
Enhancements to support Folder elements and WMS 1.3.0

### ISSUE THREAD

**Issue by lpinner** [rnz0/wms2kml#1]
Just sharing some changes I made to your original work to to support Folder elements and WMS 1.3.0 (and specifying subfolders as a parameter to limit the output KML) .

https://gist.github.com/lpinner/d8cb4390e47d220fc6fd

**Comment by rnz0** [comment]
Thanks, but I can't access the gist or it is gone.

**Comment by rnz0** [comment]
Found it:

https://gist.github.com/lpinner/5ca2b1eedf8fa5bbcdde

**Comment by lpinner** [comment]
Sorry about that, not sure what happened.
